### ISSUE TITLE
Erro Hassio 2022.9.0

### ISSUE THREAD

**Issue by djgel** [souramoo/homeassistant-milight-bluetooth#1]
Error while setting up milight_bluetooth platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/milight_bluetooth/light.py", line 51, in setup_platform
    devs.append(MiLightSm(device_config["id1"], device_config["id2"], device_config["mac"], device_config["host"], device_config["name"]))
  File "/config/custom_components/milight_bluetooth/light.py", line 99, in __init__
    self.apply()
  File "/config/custom_components/milight_bluetooth/light.py", line 193, in apply
    f = open( "./persist/"+str(self.id1), "wb" )
FileNotFoundError: [Errno 2] No such file or directory: './persist/16'

Pls,  help ?

**Comment by souramoo** [comment]
Just create a folder called persist and it should work

**Comment by djgel** [comment]
Thanks,  work in  docker,  I  change  to  .storage  and work  again !  Have  nice  day!
